version: 2
jobs:
  build:
    macos:
      xcode: "9.0"
    steps:
      - checkout
  deploy-dev:
    macos:
      xcode: "9.0"
    shell: /bin/bash --login -eo pipefail
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output/gym/
      FASTLANE_LANE: Dev
    steps:
      - checkout
      - run:
          name: Install the pods
          command: |
            curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
            pod install
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      - run:
          name: Install ruby dependancies
          command: bundle install && bundle update fastlane
      - run:
          name: Set up code signing
          command: bundle exec fastlane $FASTLANE_LANE
      - run:
          name: Deploy to hockey app
          command: hockey(api_token:"69ffd7058029458c9deb1816125d2c65", ipa:"./CircleCI2.0.ipa", notes:"Test Build")
workflows:
  version: 2
  build-deploy-dev:
    jobs:
      - build
      - deploy-dev:
          filters:
            branches:
              only: 
                - master
          requires:
            - build